### ISSUE TITLE
Getting Started Guide is not clear about project files should be created / copied for debugging.

### ISSUE THREAD

**Issue by barrcodes** [Adobe-CEP/Getting-Started-guides#12]
# Submit an issue

## Topic

This is an issue regarding:

- [x] The guides contained within this repo.
- [ ] The samples contained within this repo.

## Versions

- [ ] CEP version(s) used [must be `8.x+` for this repo]:
- [ ] Supported CC app(s) and version(s):

## Description of the issue
The getting started guide section "Launch your extension in the host app" did not have information on where to put the project files for debugging, and the information was not contained in any other area regarding the setup of the project,

## Proposed solution or attempted solutions that failed
This section should include information regarding where the project files should be copied in order to test in the host application. For instance, on Windows I believe the folder is C:\Program Files\Common Files\Adobe\CEP\extensions

**Comment by dkstevekwak** [comment]
@barrcodes The first section of the guide refers to the download location :
https://github.com/Adobe-CEP/Getting-Started-guides#1-decide-the-folder-structure
We intentionally included the link to the original document in order to not have duplicate information and keep one source of truth.
