### ISSUE TITLE
Step 6 is lacking details

### ISSUE THREAD

**Issue by sean256** [Adobe-CEP/Getting-Started-guides#16]
"6. Launch your extension in the host app"

This section is lacking the how part. How does one launch the extension?

"Package Distribute Install" does walk through the process of generating a signed zxp however I feel like this guid is eluding to a method which is not described here. Is there a way to load the extension without going through the zxp/install process for developing?

"Client-side debugging" also feels like there is a way to run an unsigned zxp easily but also fails to detail how one does it.

**Comment by dkstevekwak** [comment]
I've added a sentence describing how to run your extension without having to go through the packaging process. Hope this helps. As long as you save your folder in the path described in the first step(https://github.com/Adobe-CEP/Getting-Started-guides#6-launch-your-extension-in-the-host-app), your extension should work
