### ISSUE TITLE
Link to English Version of Indesign Scripting Guide

### ISSUE THREAD

**Issue by MarcRam** [Adobe-CEP/Getting-Started-guides#17]
# Submit an issue

## Topic

This is an issue regarding:

- [X] The guides contained within this repo.
- [ ] The samples contained within this repo.

## Description of the issue
Nihongo ga wakarimasu ka? (Do you understand Japanese?)

In Other Resources, the link for Indesign Scripting guide points to Japanese version of the documentation.

https://github.com/Adobe-CEP/Getting-Started-guides#other-resources

## Proposed solution or attempted solutions that failed

Please edit to point to English document link

https://wwwimages2.adobe.com/content/dam/acom/en/devnet/indesign/sdk/cs6/scripting/InDesign_ScriptingGuide_JS.pdf

**Comment by dkstevekwak** [comment]
@MarcRam thanks for reporting the issue. I've addressed the issue now
