### ISSUE TITLE
Why is Photoshop listed as the only product under Technology Used?

### ISSUE THREAD

**Issue by sabuncu** [Adobe-CEP/Getting-Started-guides#18]
On the main page for this repo under the **Technology Used** section (https://github.com/Adobe-CEP/Getting-Started-guides#technology-used), it says:

> Supported Host Applications: Photoshop

Is this a typo?  Isn't CEP supported by more than just the Photoshop product?

**Comment by ErinFinnegan** [comment]
Hi @sabuncu !

I think @dkstevekwak just meant that the Technology Used in this example happens to be Photoshop. Yes, of course CEP is [supported across many products](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_9.x/Documentation/CEP%209.0%20HTML%20Extension%20Cookbook.md#applications-integrated-with-cep).

We could word that differently...
