### ISSUE TITLE
Empty console with error while trying to debug CEP extension

### ISSUE THREAD

**Issue by js-jegan** [Adobe-CEP/Getting-Started-guides#22]
# Submit an issue

## Topic

This is an issue regarding:
- [ ] The guides contained within this repo.
- [ ] The samples contained within this repo.

## Versions

- [x] CEP version(s) used [must be `8.x+` for this repo]:
- [ ] Supported CC app(s) and version(s): Photoshop 21.1

## Description of the issue
Empty console with error while trying to debug CEP extension.

![image](https://user-images.githubusercontent.com/38669366/75601368-29f4cc00-5a6f-11ea-9fc6-0a44205fa3dd.png)

**Comment by ErinFinnegan** [comment]
This issue is the same as this one: https://github.com/Adobe-CEP/CEP-Resources/issues/272

Please check that thread for solutions.

**Comment by js-jegan** [comment]
⬆️ that helps!!
