### ISSUE TITLE
Extension won't show up in menu

### ISSUE THREAD

**Issue by Karmalakas** [Adobe-CEP/Getting-Started-guides#23]
This is an issue regarding the guides contained within this repo.

**Getting Started with CEP Extensions** part **5. Write Your ExtendScript Code** lacks some info.
Where does `function openDocument()` go? I assume it goes to _host/index.jsx_.

After following guide by letter and putting everything to _C:\Program Files (x86)\Common Files\Adobe\CEP\extensions\com.my.panel_, extension doesn't show up under _Window > Extensions_

Latest Ps CC
Win10 (x64)

**Comment by Karmalakas** [comment]
Figured this might be wrong place for that :/
Closing issue, will ask in forums

**Comment by ErinFinnegan** [comment]
Wait @Karmalakas ! Which forum did you post it in? Please share the link, especially if you're still stuck. 

I've been trying to monitor this forum: https://community.adobe.com/t5/exchange/ and there are many product-specific forums that are very responsive as well.

**Comment by Karmalakas** [comment]
At first posted in _[Getting started](https://community.adobe.com/t5/get-started/extension-won-t-show-up-in-menu/m-p/10970195?page=1)_, but noticed it's not about that kind of _getting started_ (just couldn't find a way to delete post). Reposted in _[Labs](https://community.adobe.com/t5/labs/extension-won-t-show-up-in-menu/m-p/10972619?page=1)_
