### ISSUE TITLE
Does Adobe provide official UI kit for extensions? 

### ISSUE THREAD

**Issue by codemilli** [Adobe-CEP/Getting-Started-guides#28]
I wanna build Adobe like UI for extensions but I cannot find anything like that.

**Comment by ErinFinnegan** [comment]
We do now! [Here's a UI kit](https://spectrum.adobe.com/page/ui-kits/).

You might also want to check out [Spectrum CSS](https://opensource.adobe.com/spectrum-css/get-started.html) or the older solution, [Topcoat](http://topcoat.io/). Many people also find [this page](https://scriptui.joonas.me/) helpful.

Also, as UXP (the Universal Extensibility Platform) rolls out to different applications over the next few years, you'll have access to each Creative Cloud App's UI components. Right now, you can only do [this in Adobe XD](https://adobexdplatform.com/plugin-docs/reference/ui/styles/using-css.html).

**Comment by codemilli** [comment]
Thanks !  @ErinFinnegan 

So [this](https://adobexdplatform.com/plugin-docs/plugin-development-guidelines/) is not for Photoshop plugin development right now. right ?

and I think this repository is not perfect guide for CEP Development because there is no information about how to communicate with PhotoShop events which I can find another site. 
Is there completed guide for CEP development?

**Comment by ErinFinnegan** [comment]
Hi @codemilli,

Yes, this: https://adobexdplatform.com/plugin-docs/plugin-development-guidelines/ is not for Photoshop plugin development _right now_. However, in a few months we hope to have something very similar in place.

So, oddly, if you want to create Photoshop-like UI, your best bet is to wait three to six months for our new "UXP" platform to roll out in Photoshop. You can follow the [Creative Cloud tag on Adobe Tech Blog](https://medium.com/adobetech/tagged/adobe-creative-cloud) or [subscribe to our developer newsletter](https://www.adobe.com/subscription/ccdevnewsletter.html) for updates.

**Comment by codemilli** [comment]
@ErinFinnegan So UXP will replace CEP?

**Comment by ErinFinnegan** [comment]
Eventually, but they will run concurrently for several years, and we do not have dates for removing CEP from products at this time.

UXP is actually for speed, modern JS, and security, the UI component is kind of a bonus.
