### ISSUE TITLE
How to keep devtools connected after reloading my extension

### ISSUE THREAD

**Issue by celeryclub** [Adobe-CEP/Getting-Started-guides#31]
# Submit an issue

## Topic

This is an issue regarding:

- [x] The guides contained within this repo.
- [ ] The samples contained within this repo.

## Versions

- [x] CEP version(s) used [must be `8.x+` for this repo]: 9.x
- [x] Supported CC app(s) and version(s): Photoshop 22 (using legacy extensions)

## Description of the issue

I'm working on a CEP extension and I have a question about debug workflows. I've followed the "Client-side debugging" doc, and everything is working as expected.
https://github.com/Adobe-CEP/Getting-Started-guides/tree/master/Client-side%20Debugging#debugging-in-chrome

However, when I make a change to the extension and disable/re-enable it in the CC app to see my changes, my devtools connection is severed and I'm shown this message: "Debugging connection was closed. Reason: WebSocket disconnected". Then I have to go back to the previous page and click the link for my extension again.

Is there a workaround for this issue that would prevent my session from being disconnected every time I reload the extension? Or perhaps there's a way to reload the extension that doesn't involve disabling/re-enabling it within the CC app?

Thanks!

## Proposed solution or attempted solutions that failed
n/a

**Comment by Stamker** [comment]
hi Steve
You can add a link with "location.reload()" code in your html file to reload the page, that will be reload the extension without losing the connection in your debug tool.
for example：` <a href="javascript:location.reload(true)">Refresh panel</a>`

**Comment by Stamker** [comment]
hi @celeryclub 
You can add a link with "location.reload()" code in your html file to reload the page, that will be reload the extension without losing the connection in your debug tool.
for example： `<a href="javascript:location.reload(true)">Refresh panel</a>`

**Comment by celeryclub** [comment]
Thanks @Stamker! That does seem to work.
